### ISSUE TITLE
Prepare NAPI for open beta testing

### ISSUE THREAD

**Issue by wnm210** [nove-org/NAPI#33]
## Prepare NAPI for open beta testing
To release open beta version of NAPI we need to finish important patches and functions. This tasklist should help.

```[tasklist]
### Checkout
- [ ] nove-org/NAPI#34
- [ ] nove-org/NAPI#35
- [ ] nove-org/NAPI#36
- [ ] https://github.com/nove-org/NAPI/issues/37
- [ ] https://github.com/nove-org/NAPI/issues/41
- [ ] https://github.com/nove-org/NAPI/issues/42
- [ ] https://github.com/nove-org/NAPI/issues/43
- [ ] https://github.com/nove-org/NAPI/issues/45
- [ ] https://github.com/nove-org/NAPI/issues/52
- [ ] https://github.com/nove-org/NAPI/issues/53
- [ ] https://github.com/nove-org/NAPI/issues/54
- [ ] https://github.com/nove-org/NAPI/issues/55
- [ ] https://github.com/nove-org/NAPI/issues/56
- [ ] https://github.com/nove-org/NAPI/issues/52
- [ ] https://github.com/nove-org/NAPI/issues/58
- [ ] https://github.com/nove-org/NAPI/issues/59
- [ ] https://github.com/nove-org/NAPI/issues/65
- [ ] https://github.com/nove-org/NAPI/issues/62
- [ ] https://github.com/nove-org/NAPI/issues/60
```
